# Numpy 
1. Numerical Python의 약자
2. 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
3. 정교한 브로드캐스팅 가능
4. 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
5. 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
6. 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [2]:
import numpy as np
np.__version__

'1.20.2'

In [3]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
a1.shape
a1[1]

[1 2 3 4 5]
<class 'numpy.ndarray'>


2

In [4]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
print(a2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [5]:
a3 = np.array([ [ [1, 2, 3], [4, 5, 6,], [7, 8, 9] ], 
                [ [1, 2, 3], [4, 5, 6,], [7, 8, 9] ], 
                [ [1, 2, 3], [4, 5, 6,], [7, 8, 9] ] ])

print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((3, 3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [11]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
print(a1)
np.zeros_like(a1)
np.full_like(a3, 10)

[1 2 3 4 5]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

In [13]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [14]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤 값으로 생성

In [16]:
np.random.random((3, 3))

array([[0.7455175 , 0.61635829, 0.98403783],
       [0.42359437, 0.24433083, 0.60485653],
       [0.64150804, 0.63416777, 0.69265649]])

In [17]:
np.random.randint(0, 10, (3, 3))

array([[9, 7, 3],
       [5, 2, 4],
       [8, 2, 5]])

In [18]:
np.random.normal(0, 1, (3, 3))

array([[ 1.74643384,  1.46108553,  0.70859487],
       [ 1.03399133,  0.66445057, -0.66192602],
       [-0.67124234,  1.160029  ,  1.58325228]])

In [19]:
np.random.rand(3, 3)

array([[0.15594649, 0.60892329, 0.19879531],
       [0.81144955, 0.52347623, 0.32860356],
       [0.07814955, 0.74749656, 0.98772488]])

In [20]:
np.random.randn(3, 3)

array([[-0.67957122, -1.59730787, -0.21523886],
       [ 0.43850774, -0.55305718, -0.09700829],
       [-0.05469733,  1.42584619, -0.08086893]])

### 표준 데이터 타입

In [21]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [23]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성

In [24]:
date = np.array('2022-01-01', dtype=np.datetime64)
date


array('2022-01-01', dtype='datetime64[D]')

In [25]:
date + np.arange(12)

array(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
       '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
       '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12'],
      dtype='datetime64[D]')

In [26]:
datetime = np.datetime64('2022-03-04 14:00')
datetime

numpy.datetime64('2022-03-04T14:00')

### 배열 조회

In [27]:
def array_info(array):
    print(array)
    print("ndim", array.ndim)
    print("shape : ", array.shape)
    print("dtype : ", array.dtype)
    print("size : ", array.size)
    print("itmesize : ", array.itemsize)
    print("nbytes : ", array.nbytes)
    print("strides : ", array.strides)

In [28]:
array_info(a1)

[1 2 3 4 5]
ndim 1
shape :  (5,)
dtype :  int32
size :  5
itmesize :  4
nbytes :  20
strides :  (4,)


In [29]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim 2
shape :  (3, 3)
dtype :  int32
size :  9
itmesize :  4
nbytes :  36
strides :  (12, 4)


In [30]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim 3
shape :  (3, 3, 3)
dtype :  int32
size :  27
itmesize :  4
nbytes :  108
strides :  (36, 12, 4)


### 인덱싱

In [31]:
print(a1[2])

3


In [32]:
print(a3)
print(a3[2, 2, 1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
8


### 슬라이싱

In [33]:
print(a1[0:2])
print(a1[::2])

[1 2]
[1 3 5]


In [34]:
print(a3[:, :2, 1])

[[2 5]
 [2 5]
 [2 5]]


### 불리언 인덱싱

In [35]:
bi = [False, True, False, False, True]
print(a1[bi])

[2 5]


In [36]:
bi = np.random.randint(0, 2, (3, 3), dtype=bool)
print(bi)
print(a2[bi])

[[ True False False]
 [ True False  True]
 [False False False]]
[1 4 6]


### 펜시 인덱싱

In [37]:
index = [0, 2]
print(a1[index])

index = np.array([[0, 1],
                [2, 0]])
print(a1[index])

[1 3]
[[1 2]
 [3 1]]


In [38]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]


### 배열값 삽입/수정/삭제/복사

In [39]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
print(a1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[1 2 3 4 5]


In [40]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0) # axis=0 : row, axis=1 : col
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [41]:
print(a1)
a1[3] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)

[1 2 3 4 5]
[1 2 3 9 5]
[1 0 3 0 0]


In [42]:
print(a2)
a2[0, 0] = 11
row = np.array([0, 1])
col = np.array([1, 1])
a2[row, col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11  0  3]
 [ 4  0  6]
 [ 7  8  9]]


In [43]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[1 0 3 0 0]
[1 3 0 0]
[1 0 3 0 0]


In [44]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)

[[11  0  3]
 [ 4  0  6]
 [ 7  8  9]]
[[11  0  3]
 [ 7  8  9]]


### 배열 복사

In [45]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2] # numpy는 실제 원본 데이터에 있는 값을 변경시킴.
a2_sub[:, 1] = 0
print(a2_sub)
print(a2) # numpy는 실제 원본 데이터에 있는 값을 변경시킴.

[[11  0  3]
 [ 4  0  6]
 [ 7  8  9]]
[[11  0]
 [ 4  0]]
[[11  0]
 [ 4  0]]
[[11  0  3]
 [ 4  0  6]
 [ 7  8  9]]


In [46]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[11  0  3]
 [ 4  0  6]
 [ 7  8  9]]
[[11  0]
 [ 4  0]]
[[11  1]
 [ 4  1]]
[[11  0  3]
 [ 4  0  6]
 [ 7  8  9]]


### 배열 변환

In [47]:
print(a2)
print(a2.T)

[[11  0  3]
 [ 4  0  6]
 [ 7  8  9]]
[[11  4  7]
 [ 0  0  8]
 [ 3  6  9]]


In [48]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [49]:
print(a2)
print(a2.swapaxes(1, 0))

[[11  0  3]
 [ 4  0  6]
 [ 7  8  9]]
[[11  4  7]
 [ 0  0  8]
 [ 3  6  9]]


In [51]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [54]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [57]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[0 1 7 6 2]
 [9 5 0 2 1]]
[[0 1]
 [7 6]
 [2 9]
 [5 0]
 [2 1]]


In [58]:
n2.resize((5, 5))
print(n2)

[[0 1 7 6 2]
 [9 5 0 2 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [59]:
n2.resize((3, 3))
print(n2)

[[0 1 7]
 [6 2 9]
 [5 0 2]]


In [60]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [61]:
c2 = np.append(a2, b2) # append는 따로 axis지정이 없으면 1차원 배열로 결합
print(c2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [62]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [63]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
