### 배열 연결

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [3]:
a2 =  np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [4]:
a2 =  np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [5]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [7]:
np.dstack([a2, a2]) # 3차원

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [8]:
np.stack([a2, a2]) # 3차원. concatenate와 stack 차이 png파일로 저장.

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

In [13]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1 = np.split(a1, [3, 6]) # 기준이 되는 index로 split
print(b1, c1, d1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1 2] [3 4 5] [6 7 8 9]


In [14]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [15]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [17]:
a3 = np.arange(1, 28).reshape(3, 3, 3) # matrix를 면이라고 생각하고 이미지화 해보면 편함.
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


### 배열 연산
- Numpy의 배열 연산은 벡터화 연산 사용
- 일반적으로 Numpy의 범용함수를 통해 구현
- 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### Broadcasting

In [26]:
# a1 = np.arange(1, 4).reshape(1, 3)
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a1 + a2)

b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산

In [29]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print(np.add(a1, 10))
print(-a1)

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]


In [31]:
a1 = np.arange(1, 10)
b1 = np.random.randint(1, 10, size=9)
print(a1)
print(b1)
print(a1 * b1)

[1 2 3 4 5 6 7 8 9]
[6 9 2 1 6 5 5 4 2]
[ 6 18  6  4 30 30 35 32 18]


In [34]:
a2 = np.arange(1, 10).reshape(3, 3)
b2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(b2)
print(a2 * b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[6 4 1]
 [4 2 6]
 [4 6 9]]
[[ 6  8  3]
 [16 10 36]
 [28 48 81]]


In [36]:
a1 = np.random.randint(-10, 0, size=5)
print(a1)
print(np.abs(a1))

[ -6 -10  -3  -7  -6]
[ 6 10  3  7  6]


In [38]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[6 8 4 9 3]
[ 403.42879349 2980.95798704   54.59815003 8103.08392758   20.08553692]
[ 64. 256.  16. 512.   8.]
[36 64 16 81  9]


In [41]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[6 8 4 9 3]
[1.79175947 2.07944154 1.38629436 2.19722458 1.09861229]
[2.5849625 3.        2.        3.169925  1.5849625]
[0.77815125 0.90308999 0.60205999 0.95424251 0.47712125]


### 삼각함수

In [42]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [43]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계함수

In [49]:
a2 = np.random.randint(1, 10, size=(3, 3))
b2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(b2)
print(np.tensordot(a2, b2)) # 벡터의 내적 (스칼라값)
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[1 6 3]
 [5 4 1]
 [9 6 1]]
[[9 8 2]
 [7 2 8]
 [7 4 9]]
210
[[[[ 9  8  2]
   [ 7  2  8]
   [ 7  4  9]]

  [[54 48 12]
   [42 12 48]
   [42 24 54]]

  [[27 24  6]
   [21  6 24]
   [21 12 27]]]


 [[[45 40 10]
   [35 10 40]
   [35 20 45]]

  [[36 32  8]
   [28  8 32]
   [28 16 36]]

  [[ 9  8  2]
   [ 7  2  8]
   [ 7  4  9]]]


 [[[81 72 18]
   [63 18 72]
   [63 36 81]]

  [[54 48 12]
   [42 12 48]
   [42 24 54]]

  [[ 9  8  2]
   [ 7  2  8]
   [ 7  4  9]]]]
[[ 72  32  77]
 [ 80  52  51]
 [130  88  75]]


In [50]:
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y)) # 벡터의 외적

[-3  6 -3]


### 비교연산

In [52]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
